In [0]:
import numpy as np
size = int(input())

A = np.random.random((size,size))
B = np.zeros((size//2, size//2))
print(A)

for i in range(size//2):
    for j in range(size//2):
        B[i, j] = np.max(A[i*2 : i*2 +2, j*2 : j*2 + 2])
        

print(B)
        



4
[[0.82592118 0.29800067 0.97758609 0.70074631]
 [0.90074703 0.08004422 0.04723443 0.1160088 ]
 [0.88546882 0.79283146 0.5450512  0.60682699]
 [0.06479744 0.83107665 0.53969639 0.71697906]]
[[0.90074703 0.97758609]
 [0.88546882 0.71697906]]
